import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { StyledEngineProvider, ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import "@/styles/globals.css";
import { CssBaseline } from "@mui/material";
import { TLanguage } from "@/locale/locale";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: TLanguage };
}>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        {/* <AppRouterCacheProvider
            options={{ key: 'css' }}
          >
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider> */}
        <StyledEngineProvider>
          <CssBaseline />
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
